FROM arm32v7/python

WORKDIR /app
COPY . .
RUN apt-get install tzdata \
  && cp /usr/share/zoneinfo/Europe/Bucharest /etc/localtime \
  && echo "Europe/Bucharest" > /etc/timezone \
  && pip install -r requirements.txt

CMD [ "python", "ursar.py" ]